package lexer.token;

public enum TokenType {
    INT, LONG, FLOAT, DOUBLE, STRING, BOOLEAN, CHAR,
    INT_LIT, LONG_LIT, FLOAT_LIT, DOUBLE_LIT, STRING_LIT, CHAR_LIT, BOOL_LIT, NULL_LIT,
    ARRAY, IDENTIFIER,
    FUNCTION,
    TRUE, FALSE, OR,
    MAIN, RETURN, SCAN, PRINT, IF, ELSE, WHILE, BREAK,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF
    /*
    INT, LONG, FLOAT, DOUBLE, STRING, BOOLEAN, CHAR, ARRAY, IDENTIFIER,
    FUNCTION,
    TRUE, FALSE, OR,
    MAIN, RETURN, SCAN, PRINT, IF, ELSE, WHILE, BREAK,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF
*/

    /*
    INT, BEGIN, END, FUNCTION, IF, OR, ELSE, FOR, GOES, FROM, TO, CALL, RETURN,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF*/
}
